FROM python:3.9-slim

WORKDIR /app

# Instalar dependencias
RUN pip install faker requests python-dateutil

# Copiar generador de logs
COPY src/collectors/log_generator.py .

# Crear directorio para logs
RUN mkdir -p /app/logs

# Comando por defecto
CMD ["python", "log_generator.py"]