version: 2

sources:
  - name: public
    database: youtube_dwh
    schema: public
    tables:
      - name: raw_youtube_videos

models:
  - name: stg_yt_videos
    description: "Staging model for YouTube trending videos, with basic cleaning."
    columns:
      - name: video_id
        description: "Unique identifier for the video."
        tests:
          - unique
          - not_null
      - name: trending_date
        description: "Date when the video was trending."
        tests:
          - not_null
      - name: views
        description: "Number of views the video received."
        tests:
          - not_null
          - dbt_utils.at_least_one:
              column_name: views
              expression: "views > 0"

  - name: fct_video_trends
    description: "Fact table for YouTube video trends, with calculated metrics."
    columns:
      - name: video_id
        description: "Unique identifier for the video."
        tests:
          - unique
          - not_null
      - name: engagement_rate
        description: "Calculated engagement rate for the video."
        tests:
          - not_null
          - dbt_utils.at_least_one:
              column_name: engagement_rate
              expression: "engagement_rate >= 0"
