# Configuración de Filebeat para colección de logs de seguridad

filebeat.inputs:
# Logs de servidor web
- type: log
  enabled: true
  paths:
    - /var/log/security/web.log
  fields:
    log_type: web
    source: apache
  fields_under_root: true
  multiline.pattern: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
  multiline.negate: true
  multiline.match: after

# Logs de firewall
- type: log
  enabled: true
  paths:
    - /var/log/security/firewall.log
  fields:
    log_type: firewall
    source: iptables
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true

# Logs de autenticación
- type: log
  enabled: true
  paths:
    - /var/log/security/auth.log
  fields:
    log_type: auth
    source: sshd
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true

# Logs de sistema
- type: log
  enabled: true
  paths:
    - /var/log/security/system.log
  fields:
    log_type: system
    source: windows_events
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true

# Logs DNS
- type: log
  enabled: true
  paths:
    - /var/log/security/dns.log
  fields:
    log_type: dns
    source: bind
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true

# Configuración de salida a Logstash
output.logstash:
  hosts: ["logstash:5044"]
  
# Configuración de logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Configuración de procesadores
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - timestamp:
      field: timestamp
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05Z'
      test:
        - '2023-10-15T14:30:45.123Z'

# Configuración de monitoreo
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "password"

# Configuración de template
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  _source.enabled: true